name: Deploy Terraform

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - 'src/**'

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_S3_STATE_BUCKET_NAME: ${{ secrets.S3_STATE_BUCKET_NAME }}
      TF_VAR_SSM_TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TF_VAR_SSM_TWILIO_AUTH_KEY: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TF_VAR_SSM_TWILIO_RECIPIENT: ${{ secrets.TWILIO_RECIPIENT }}
      TF_VAR_SSM_TWILIO_SENDER: ${{ secrets.TWILIO_SENDER }}
      TF_VAR_ATLASSIAN_EMAIL_ID: ${{ secrets.ATLASSIAN_EMAIL_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Create temporary dir for function layer # Needs to be called `python`
        run: mkdir -p python

      - name: Create function layer
        run: | 
          cd python
          pip install -r ../requirements.txt -t .
          
          ls -a
          cd ..
          zip -r aws-infra/python.zip ./python

      - name: Zip Function source
        run: |
          cd src
          zip -r ../aws-infra/function_code.zip .

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialise Terraform
        run: |
          cd aws-infra
          terraform init -backend-config="bucket=tf-state-bucket-2213"
      #terraform destroy -auto-approve
      
      - name: Apply Terraform
        run: |
          cd aws-infra
          terraform apply -auto-approve
    

