name: Deploy Terraform

on:
  push:
    paths:
      - '**/*.tf'

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_AUTH_KEY: ${{ secrets.TWILIO_AUTH_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: |
          terraform apply -auto-approve \
            -var "TWILIO_SID=${TWILIO_SID}" \
            -var "TWILIO_AUTH_KEY=${TWILIO_AUTH_KEY}"

      - name: Clean up
        run: terraform destroy -auto-approve
