name: Terraform Plan (PR)

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - 'rental-alerts/**'

jobs:
  plan-tf:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      TF_VAR_S3_STATE_BUCKET_NAME: ${{ secrets.S3_STATE_BUCKET_NAME }}
      TF_VAR_SSM_TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TF_VAR_SSM_TWILIO_AUTH_KEY: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TF_VAR_SSM_TWILIO_RECIPIENT: ${{ secrets.TWILIO_RECIPIENT }}
      TF_VAR_SSM_TWILIO_SENDER: ${{ secrets.TWILIO_SENDER }}

      TF_VAR_ATLASSIAN_EMAIL_ID: ${{ secrets.ATLASSIAN_EMAIL_ID }}

      TF_VAR_SMTP_SENDER_EMAIL: ${{ secrets.SMTP_SENDER_EMAIL }}
      TF_VAR_SMTP_SENDER_KEY: ${{ secrets.SMTP_SENDER_KEY }}
      TF_VAR_SMTP_RECIPIENT_EMAIL: ${{ secrets.SMTP_RECIPIENT_EMAIL }}

      TF_IN_AUTOMATION: "True"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform init
      id: init
      run: |
        cd aws-infra
        terraform init -backend-config="bucket=${{ secrets.S3_STATE_BUCKET_NAME }}"
        
    - name: Run terraform plan
      id: plan
      run: |
        cd aws-infra
        echo 'plan<<EOF' >> $GITHUB_OUTPUT
        terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
        
    - name: Comment Plan
      id: comment-plan
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Terraform Plan:
          ```
          ${{ steps.plan.outputs.plan }}
          ```
          Merge this PR to apply these changes.
